american2middleeastern = {'bacon': 'lamb bacon', 'pork': 'lamb', 'ham': 'lamb ham',
        'bacon grease': 'olive oil', 'canola oil': 'olive oil', 'vegetable oil': 'olive oil',
        'American cheese': 'feta cheese', 'cheddar': 'feta', 'blue cheese': 'feta cheese',
        'cheese curd': 'feta', 'colby': 'feta', 'colby-jack': 'labneh', 'cream cheese': 'halloumi',
        'monterey jack': 'ackawi', 'pepper jack cheese': 'nabulsi', 'string cheese': 'jibneh arabieh',
        'parmesan': 'testouri', 'swiss cheese': 'shanklish', 'nacho cheese': 'hummus',
        'pink bean': 'chickpea', 'pinquito': 'chickpea', 'ketchup': 'tomato', 'mustard': 'sumac',
        'paprika': 'cumin', 'oregano': 'parsley', 'tortilla': 'pita', 'yogurt': 'greek yogurt',
        'mayonnaise': 'tahini', 'jalapeno pepper': 'peppercorn', 'navy bean': 'chickpea',
        'molasse': 'honey', 'syrup': 'honey', 'mustard': 'cumin', 'worcestershire sause': 'tahini',
        'brown sugar': 'honey', 'powdered sugar': 'honey', 'granulated sugar': 'honey',
        'hot sauce': 'tahini', 'hot pepper sauce': 'tahini', 'bratwurst': 'lamb sausage',
        'grits': 'rice', 'white sugar': 'honey', 'cornmeal': 'chickpea flour',
        'oatmeal': 'rice', 'bread': 'pita bread', 'squash': 'cucumber', 'zucchini': 'cucumber',
        'pickle': 'olive', 'bell pepper': 'cucumber', 'shrimp': 'beef', 'whipping cream': 'honey',
        'whipped cream': 'honey', 'heavy cream': 'whole milk', 'green onion': 'coriander',
        'corn flour': 'wheat flour', 'cornmeal': 'rice', 'chocolate chips': 'mixed nuts',
        'hamburger bun': 'pita bread', 'hotdog bun': 'pita bread', 'sour cream': 'coconut cream',
        'celery': 'okra', 'crackers': 'pita chips', 'maple syrup': 'honey', 'soy sauce': 'sesame oil',
        'coleslaw mix': 'cucumber tomato mix', 'salad dressing': 'sesami oil', 'poppy seeds': 'cumin',
        'half-and-half': 'goatmilk', 'sweet potato': 'carrot', 'pie crust': 'baklava crust', 
        'cooking sherry': 'nutmeg', 'linguine pasta': 'couscous', 'spaghetti': 'couscous',
        'cookie dough': 'phyllo dough', 'basil': 'thyme', 'asparagus': 'okra', 'balsamic vinegar': 'sumac',
        'andoille sausage': 'lamb sausage', 'cilantro': 'coriander', 'salsa': 'hummus',
        'bay leaves': 'cinnamon', 'kidney bean': 'black bean', 'garbanzo bean': 'chickpea',
        'bread dough': 'phyllo dough', 'italian sausage': 'beef kebab', 'fennel seed': 'cinnamon',
        'oats': 'mujadara pilaf', 'steak': 'shish kabob', 'pizza dough': 'pita bread dough',
        'house salad': 'tabouli salad', 'salsa dip': 'tabouli salad', 'ricotta cheese': 'feta cheese',
        'enchilada sauce': 'hummus'}
